<div class="panel home ">
  <div class="section">
    <h1 class="title">Welcome to FroSoCo</h1>

	<div class="alert alert-info">
    Welcome new and returning residents! <a href="https://frosoco.stanford.edu/assets/documents/FSC_Roommate_Contract_1516.pdf">Click here for Roommate Contracts</a> and <a href="https://frosoco.stanford.edu/home/policies">here for Dorm Policies!</a>
  </div>

    <? if ($this->session->userdata('id')) { // if authorized ?>
      <!-- notif-->
      <!-- <div class="alert alert-info">See our</div>-->
    <? } ?>

    <p>
     The Freshman-Sophomore College has the vibrant residential intellectual community of a small, elite, liberal-arts college while providing enhanced access to the academic resources of one of the world's premier research universities.
   </p>

   <p>
     In addition to all of the energy and excitement that typifies the freshman-year experience, FroSoCo is specifically designed to create a close-knit community by bringing together the most talented students at Stanford and then helping them achieve a balance of academic preparation, personal exploration, cultural enrichment, and self-reflection at the highest level. They emerge with the critical self-understanding needed for the life-long project of designing a meaningful life and are already connected to the resources at Stanford that can set them on the path towards being exceptional individuals and community leaders.
   </p>

   <p>
    Part of what helps us achieve these goals is a fun community of students that share their extraordinary abilities and help each other develop, flourish and enjoy life: at the College you will live, study, and play with like-minded individuals who are academically driven, excited about the arts, give back to their community, play Frisbee in the Quad, build a trebuchet to apply their knowledge of physics, attend plays, sporting events, concerts, restaurants - all supported by the College and its extensive staff. Each house of the college has a senior staff or faculty couple, our College Directors, that live in attached residences; the College Dean lives across from the College.
  </p>

  <p>
    Along with the regular student staff, we also have a public speaking tutor and a multimedia consultant. In addition to the wide range of workshops and tutorials provided by our staff, our sophomores lead mini-seminars on a diverse array of subjects exclusively for our residents. The College brings in distinguished professors, entrepreneurs, community leaders, and artists to meet with the students and have dinner with them at the Dean's residence.
  </p>
</div><!--section-->
</div>

<div id="sidebar" >
 <div class="panel feed">

  <div class="feed-highlight section">
    <div style='position: relative; padding-bottom: 71%; height: 0; overflow: hidden;'>
      <iframe id='iframe' src='https://flickrit.com/slideshowholder.php?height=70&size=big&setId=72157658832902066&thumbnails=0&transition=0&layoutType=responsive&sort=0' scrolling='no' frameborder='0'style='width:100%; height:100%; position: absolute; top:0; left:0;' >
      </iframe>
    </div><!--flkr slideshow, generated by flickrit.com/-->
  </div>
  <div class="section">
    <div class="feed-notification">
      Check us out on <a href="https://www.facebook.com/stanford.frosoco">Facebook!</a>
    </div>
    <div class="feed-notification">Looking for classes? Check out <a href="http://explorecourses.stanford.edu/">
      ExploreCourses.</a>
    </div>
    <div class="feed-notification">If you're mailing items, follow the
      <a href="http://web.stanford.edu/dept/rde/cgi-bin/drupal/housing/move/mail-delivery-and-shipping">
        instructions from Student Housing.
      </a>
    </div>
    <div class="feed-notification"><b>Address</b> (not for mailing):
      <p>&nbsp; &nbsp; &nbsp; 236 Santa Teresa St <br/>
        &nbsp; &nbsp; &nbsp; Stanford, CA 94305
      </p>
    </div>
  </div>
</div>
</div>

